title: Kaleidotype
description: "Looking at the progression of logos throughout time. "
footer_text: Copyright 2021 Kaia Blaszczyk
header_feature_image: ../uploads/new-project.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/new-project-3.png
favicon: ../uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
items:
  - name: About me
    siteurl: /aboutme/
